### ISSUE TITLE
snap connection for personal files

### ISSUE THREAD

**Issue by Fuseteam** [fredldotme/git-confined-snap#1]
I like to place my source directories into `~/.local/src` as i consider that the local user equivalent of `/usr/local/src` but due to snap's confinement the access to it is denied.

It appears [the home interface only permits access to non-hidden files and directories](https://askubuntu.com/a/1238219/414411) to give it access to the hidden folders we'll need the personal files interface

**Comment by fredldotme** [comment]
I am not sure it's possible to do this fairly without opening up a can of worms. If other users have then again completely different setups then it becomes impossible to maintain all possible variations.

**Comment by Fuseteam** [comment]
Not many variations with this one, you have home with hidden directories or home without hidden directories. You could replace `home` with `personal-files` to keep it simple. if i understand it correctly the latter is a superset of the former

**Comment by fredldotme** [comment]
No what I mean is someone else might come along and claim "but you enabled .local/src, how about my .local/src-because-I-wont-comply"

EDIT: Alright, if you provide a PR I'll see what we can do, but it will require permission by the Snap Store team.

**Comment by Fuseteam** [comment]
> No what I mean is someone else might come along and claim "but you enabled .local/src, how about my .local/src-because-I-wont-comply"

Oh both would be covered by personal-files, if i understand correctly

**Comment by Fuseteam** [comment]
> EDIT: Alright, if you provide a PR I'll see what we can do, but it will require permission by the Snap Store team.

Do you want to me to add it as an additional plug or to replace home with it?

**Comment by Fuseteam** [comment]
Fixed with #2
